// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkpwmKawrtrC6_qX01BzWFx1rore4eOVs',
    appId: '1:1017364604472:android:7b948f18beecf2952728cd',
    messagingSenderId: '1017364604472',
    projectId: 'verde-login',
    databaseURL: 'https://verde-login-default-rtdb.firebaseio.com',
    storageBucket: 'verde-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASVHFXh18yJa5zuhL4_Dl9gDOsvUoQbOY',
    appId: '1:1017364604472:ios:c983d5585ddf596b2728cd',
    messagingSenderId: '1017364604472',
    projectId: 'verde-login',
    databaseURL: 'https://verde-login-default-rtdb.firebaseio.com',
    storageBucket: 'verde-login.appspot.com',
    iosClientId: '1017364604472-h8e851t3ookhq88ngr1kfeh4c68pd01d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSingleton',
  );
}
