name: verdemvpapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  flutter_appauth: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^5.3.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images